/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_if = 4,
  anon_sym_limit = 5,
  anon_sym_trigger = 6,
  anon_sym_potential = 7,
  anon_sym_AND = 8,
  anon_sym_OR = 9,
  anon_sym_NOT = 10,
  anon_sym_LBRACK_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_template_string = 13,
  sym_string = 14,
  sym_number = 15,
  anon_sym_yes = 16,
  anon_sym_no = 17,
  anon_sym_true = 18,
  anon_sym_false = 19,
  anon_sym_DOLLAR = 20,
  sym_identifier = 21,
  sym_comment = 22,
  sym_source_file = 23,
  sym_assignment = 24,
  sym_map = 25,
  sym_statement = 26,
  sym_array = 27,
  sym_simple_value = 28,
  sym_condition_statement = 29,
  sym_logical_statement = 30,
  sym_macro_map = 31,
  sym_boolean = 32,
  sym_variable = 33,
  sym_variable_embedded_identifier = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_map_repeat1 = 36,
  aux_sym_array_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_limit] = "limit",
  [anon_sym_trigger] = "trigger",
  [anon_sym_potential] = "potential",
  [anon_sym_AND] = "AND",
  [anon_sym_OR] = "OR",
  [anon_sym_NOT] = "NOT",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK] = "]",
  [sym_template_string] = "template_string",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_yes] = "yes",
  [anon_sym_no] = "no",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DOLLAR] = "$",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_assignment] = "assignment",
  [sym_map] = "map",
  [sym_statement] = "statement",
  [sym_array] = "array",
  [sym_simple_value] = "simple_value",
  [sym_condition_statement] = "condition_statement",
  [sym_logical_statement] = "logical_statement",
  [sym_macro_map] = "macro_map",
  [sym_boolean] = "boolean",
  [sym_variable] = "variable",
  [sym_variable_embedded_identifier] = "variable_embedded_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_limit] = anon_sym_limit,
  [anon_sym_trigger] = anon_sym_trigger,
  [anon_sym_potential] = anon_sym_potential,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_template_string] = sym_template_string,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_assignment] = sym_assignment,
  [sym_map] = sym_map,
  [sym_statement] = sym_statement,
  [sym_array] = sym_array,
  [sym_simple_value] = sym_simple_value,
  [sym_condition_statement] = sym_condition_statement,
  [sym_logical_statement] = sym_logical_statement,
  [sym_macro_map] = sym_macro_map,
  [sym_boolean] = sym_boolean,
  [sym_variable] = sym_variable,
  [sym_variable_embedded_identifier] = sym_variable_embedded_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_limit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trigger] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_potential] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_template_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_value] = {
    .visible = true,
    .named = true,
  },
  [sym_condition_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_map] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_embedded_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_top_level_statement = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_top_level_statement] = "top_level_statement",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_top_level_statement, 0},
  [1] =
    {field_top_level_statement, 0, .inherited = true},
  [2] =
    {field_top_level_statement, 0, .inherited = true},
    {field_top_level_statement, 1, .inherited = true},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_key, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 14,
  [19] = 13,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 15,
  [28] = 10,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 16,
  [42] = 42,
  [43] = 15,
  [44] = 23,
  [45] = 45,
  [46] = 17,
  [47] = 14,
  [48] = 13,
  [49] = 10,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 57,
  [61] = 55,
  [62] = 55,
};

static const TSCharacterRange sym_identifier_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'%', '<'}, {'>', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 1,
        '#', 75,
        '$', 33,
        '-', 34,
        '.', 72,
        '=', 12,
        'A', 36,
        'N', 37,
        'O', 38,
        '[', 8,
        ']', 23,
        'f', 40,
        'i', 47,
        'l', 50,
        'n', 59,
        'p', 60,
        't', 61,
        'y', 42,
        '{', 13,
        '}', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 3,
        '#', 75,
        '$', 33,
        '-', 34,
        '.', 72,
        '=', 12,
        'f', 40,
        'n', 59,
        't', 63,
        'y', 42,
        '{', 13,
        '}', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(74);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '=' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(74);
      END_STATE();
    case 8:
      if (lookahead == '[') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 1,
        '#', 75,
        '$', 33,
        '-', 34,
        '.', 72,
        '=', 12,
        'A', 36,
        'N', 37,
        'O', 38,
        '[', 8,
        ']', 23,
        'i', 47,
        'l', 50,
        'p', 60,
        't', 64,
        '{', 13,
        '}', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_if);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_limit);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_trigger);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_potential);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_AND);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_OR);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_NOT);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_template_string);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(72);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_yes);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_no);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_true);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_false);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(19);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N') ADVANCE(35);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(39);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(20);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(21);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(56);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(55);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(65);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(31);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(32);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(62);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(15);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(49);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(46);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(57);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'u') ADVANCE(44);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(48);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(67);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(41);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(18);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(66);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(53);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(69);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(30);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(68);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(51);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(17);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(70);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(52);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(29);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(45);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(16);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(43);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(54);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(44);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(75);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_limit] = ACTIONS(1),
    [anon_sym_trigger] = ACTIONS(1),
    [anon_sym_potential] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_template_string] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(52),
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(36),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_template_string] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(5),
    [sym_simple_value] = STATE(38),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_boolean] = STATE(44),
    [sym_variable] = STATE(12),
    [sym_variable_embedded_identifier] = STATE(11),
    [aux_sym_map_repeat1] = STATE(5),
    [aux_sym_array_repeat1] = STATE(38),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_template_string] = ACTIONS(17),
    [sym_string] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
    [anon_sym_yes] = ACTIONS(31),
    [anon_sym_no] = ACTIONS(31),
    [anon_sym_true] = ACTIONS(31),
    [anon_sym_false] = ACTIONS(31),
    [anon_sym_DOLLAR] = ACTIONS(33),
    [sym_identifier] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(3),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_if] = ACTIONS(43),
    [anon_sym_limit] = ACTIONS(43),
    [anon_sym_trigger] = ACTIONS(43),
    [anon_sym_potential] = ACTIONS(43),
    [anon_sym_AND] = ACTIONS(46),
    [anon_sym_OR] = ACTIONS(46),
    [anon_sym_NOT] = ACTIONS(46),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(49),
    [anon_sym_RBRACK] = ACTIONS(41),
    [sym_template_string] = ACTIONS(52),
    [sym_string] = ACTIONS(55),
    [sym_number] = ACTIONS(58),
    [anon_sym_DOLLAR] = ACTIONS(61),
    [sym_identifier] = ACTIONS(58),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(36),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(64),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_template_string] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(3),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_template_string] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(36),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(68),
    [anon_sym_EQ] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_if] = ACTIONS(76),
    [anon_sym_limit] = ACTIONS(76),
    [anon_sym_trigger] = ACTIONS(76),
    [anon_sym_potential] = ACTIONS(76),
    [anon_sym_AND] = ACTIONS(79),
    [anon_sym_OR] = ACTIONS(79),
    [anon_sym_NOT] = ACTIONS(79),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(82),
    [sym_template_string] = ACTIONS(85),
    [sym_string] = ACTIONS(88),
    [sym_number] = ACTIONS(91),
    [anon_sym_DOLLAR] = ACTIONS(94),
    [sym_identifier] = ACTIONS(91),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(3),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(97),
    [sym_template_string] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(7),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(99),
    [sym_template_string] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym_assignment] = STATE(24),
    [sym_map] = STATE(22),
    [sym_statement] = STATE(5),
    [sym_condition_statement] = STATE(24),
    [sym_logical_statement] = STATE(24),
    [sym_macro_map] = STATE(24),
    [sym_variable] = STATE(30),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_template_string] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_identifier] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [anon_sym_EQ] = ACTIONS(103),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_if] = ACTIONS(105),
    [anon_sym_limit] = ACTIONS(105),
    [anon_sym_trigger] = ACTIONS(105),
    [anon_sym_potential] = ACTIONS(105),
    [anon_sym_AND] = ACTIONS(105),
    [anon_sym_OR] = ACTIONS(105),
    [anon_sym_NOT] = ACTIONS(105),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(103),
    [sym_template_string] = ACTIONS(103),
    [sym_string] = ACTIONS(105),
    [sym_number] = ACTIONS(105),
    [anon_sym_yes] = ACTIONS(105),
    [anon_sym_no] = ACTIONS(105),
    [anon_sym_true] = ACTIONS(105),
    [anon_sym_false] = ACTIONS(105),
    [anon_sym_DOLLAR] = ACTIONS(103),
    [sym_identifier] = ACTIONS(105),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [anon_sym_EQ] = ACTIONS(107),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_if] = ACTIONS(115),
    [anon_sym_limit] = ACTIONS(115),
    [anon_sym_trigger] = ACTIONS(115),
    [anon_sym_potential] = ACTIONS(115),
    [anon_sym_AND] = ACTIONS(115),
    [anon_sym_OR] = ACTIONS(115),
    [anon_sym_NOT] = ACTIONS(115),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(110),
    [sym_template_string] = ACTIONS(110),
    [sym_string] = ACTIONS(117),
    [sym_number] = ACTIONS(117),
    [anon_sym_yes] = ACTIONS(120),
    [anon_sym_no] = ACTIONS(120),
    [anon_sym_true] = ACTIONS(120),
    [anon_sym_false] = ACTIONS(120),
    [anon_sym_DOLLAR] = ACTIONS(112),
    [sym_identifier] = ACTIONS(117),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [anon_sym_EQ] = ACTIONS(107),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_if] = ACTIONS(115),
    [anon_sym_limit] = ACTIONS(115),
    [anon_sym_trigger] = ACTIONS(115),
    [anon_sym_potential] = ACTIONS(115),
    [anon_sym_AND] = ACTIONS(115),
    [anon_sym_OR] = ACTIONS(115),
    [anon_sym_NOT] = ACTIONS(115),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(110),
    [sym_template_string] = ACTIONS(110),
    [sym_string] = ACTIONS(117),
    [sym_number] = ACTIONS(122),
    [anon_sym_yes] = ACTIONS(120),
    [anon_sym_no] = ACTIONS(120),
    [anon_sym_true] = ACTIONS(120),
    [anon_sym_false] = ACTIONS(120),
    [anon_sym_DOLLAR] = ACTIONS(112),
    [sym_identifier] = ACTIONS(122),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [anon_sym_EQ] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(126),
    [anon_sym_RBRACE] = ACTIONS(126),
    [anon_sym_if] = ACTIONS(128),
    [anon_sym_limit] = ACTIONS(128),
    [anon_sym_trigger] = ACTIONS(128),
    [anon_sym_potential] = ACTIONS(128),
    [anon_sym_AND] = ACTIONS(128),
    [anon_sym_OR] = ACTIONS(128),
    [anon_sym_NOT] = ACTIONS(128),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(126),
    [sym_template_string] = ACTIONS(126),
    [sym_string] = ACTIONS(128),
    [sym_number] = ACTIONS(128),
    [anon_sym_yes] = ACTIONS(128),
    [anon_sym_no] = ACTIONS(128),
    [anon_sym_true] = ACTIONS(128),
    [anon_sym_false] = ACTIONS(128),
    [anon_sym_DOLLAR] = ACTIONS(126),
    [sym_identifier] = ACTIONS(128),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [anon_sym_EQ] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(126),
    [anon_sym_RBRACE] = ACTIONS(126),
    [anon_sym_if] = ACTIONS(128),
    [anon_sym_limit] = ACTIONS(128),
    [anon_sym_trigger] = ACTIONS(128),
    [anon_sym_potential] = ACTIONS(128),
    [anon_sym_AND] = ACTIONS(128),
    [anon_sym_OR] = ACTIONS(128),
    [anon_sym_NOT] = ACTIONS(128),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(126),
    [sym_template_string] = ACTIONS(126),
    [sym_string] = ACTIONS(128),
    [sym_number] = ACTIONS(130),
    [anon_sym_yes] = ACTIONS(128),
    [anon_sym_no] = ACTIONS(128),
    [anon_sym_true] = ACTIONS(128),
    [anon_sym_false] = ACTIONS(128),
    [anon_sym_DOLLAR] = ACTIONS(126),
    [sym_identifier] = ACTIONS(130),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [anon_sym_EQ] = ACTIONS(133),
    [anon_sym_LBRACE] = ACTIONS(133),
    [anon_sym_RBRACE] = ACTIONS(133),
    [anon_sym_if] = ACTIONS(135),
    [anon_sym_limit] = ACTIONS(135),
    [anon_sym_trigger] = ACTIONS(135),
    [anon_sym_potential] = ACTIONS(135),
    [anon_sym_AND] = ACTIONS(135),
    [anon_sym_OR] = ACTIONS(135),
    [anon_sym_NOT] = ACTIONS(135),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(133),
    [sym_template_string] = ACTIONS(133),
    [sym_string] = ACTIONS(135),
    [sym_number] = ACTIONS(135),
    [anon_sym_yes] = ACTIONS(135),
    [anon_sym_no] = ACTIONS(135),
    [anon_sym_true] = ACTIONS(135),
    [anon_sym_false] = ACTIONS(135),
    [anon_sym_DOLLAR] = ACTIONS(133),
    [sym_identifier] = ACTIONS(135),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [sym_variable] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(137),
    [anon_sym_EQ] = ACTIONS(137),
    [anon_sym_LBRACE] = ACTIONS(137),
    [anon_sym_RBRACE] = ACTIONS(137),
    [anon_sym_if] = ACTIONS(139),
    [anon_sym_limit] = ACTIONS(139),
    [anon_sym_trigger] = ACTIONS(139),
    [anon_sym_potential] = ACTIONS(139),
    [anon_sym_AND] = ACTIONS(139),
    [anon_sym_OR] = ACTIONS(139),
    [anon_sym_NOT] = ACTIONS(139),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(137),
    [anon_sym_RBRACK] = ACTIONS(137),
    [sym_template_string] = ACTIONS(137),
    [sym_string] = ACTIONS(139),
    [sym_number] = ACTIONS(139),
    [anon_sym_DOLLAR] = ACTIONS(141),
    [sym_identifier] = ACTIONS(139),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(146), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [26] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      sym_number,
      sym_identifier,
    ACTIONS(126), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(128), 8,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
  [54] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(128), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [80] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(153), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [106] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(157), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [132] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(161), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [158] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(139), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [184] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(115), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(165), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [236] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      sym_number,
      sym_identifier,
    ACTIONS(163), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(165), 8,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
  [264] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(135), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [290] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(105), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(172), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [342] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_EQ,
    ACTIONS(174), 2,
      sym_number,
      sym_identifier,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(115), 8,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
  [372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(180), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [398] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_EQ,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(115), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(185), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [452] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(189), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [478] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 8,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(193), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [504] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 6,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACK_LBRACK,
      sym_template_string,
      anon_sym_DOLLAR,
    ACTIONS(197), 10,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_string,
      sym_number,
      sym_identifier,
  [528] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(201), 1,
      sym_string,
    STATE(23), 1,
      sym_boolean,
    STATE(26), 1,
      sym_variable,
    ACTIONS(203), 2,
      sym_number,
      sym_identifier,
    ACTIONS(205), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 4,
      sym_map,
      sym_array,
      sym_simple_value,
      sym_variable_embedded_identifier,
  [563] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      sym_string,
    ACTIONS(213), 1,
      anon_sym_DOLLAR,
    STATE(44), 1,
      sym_boolean,
    STATE(45), 1,
      sym_variable,
    ACTIONS(211), 2,
      sym_number,
      sym_identifier,
    STATE(39), 3,
      sym_simple_value,
      sym_variable_embedded_identifier,
      aux_sym_array_repeat1,
    ACTIONS(31), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [597] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    ACTIONS(217), 1,
      sym_string,
    ACTIONS(226), 1,
      anon_sym_DOLLAR,
    STATE(44), 1,
      sym_boolean,
    STATE(45), 1,
      sym_variable,
    ACTIONS(220), 2,
      sym_number,
      sym_identifier,
    STATE(39), 3,
      sym_simple_value,
      sym_variable_embedded_identifier,
      aux_sym_array_repeat1,
    ACTIONS(223), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [631] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_EQ,
    ACTIONS(231), 1,
      anon_sym_DOLLAR,
    STATE(14), 1,
      sym_variable,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(139), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [656] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOLLAR,
    STATE(47), 1,
      sym_variable,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(139), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [678] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_EQ,
    ACTIONS(137), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(139), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(135), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(139), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [732] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      sym_number,
      sym_identifier,
    ACTIONS(237), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(120), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [751] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(146), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [768] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 2,
      sym_number,
      sym_identifier,
    ACTIONS(126), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(128), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(128), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(105), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [821] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(229), 1,
      anon_sym_EQ,
    STATE(18), 1,
      sym_variable,
  [834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_map,
  [844] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
  [851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_EQ,
  [858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACK,
  [865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
  [872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_EQ,
  [879] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_DOLLAR,
  [886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_identifier,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_DOLLAR,
  [900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_DOLLAR,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_identifier,
  [914] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 26,
  [SMALL_STATE(19)] = 54,
  [SMALL_STATE(20)] = 80,
  [SMALL_STATE(21)] = 106,
  [SMALL_STATE(22)] = 132,
  [SMALL_STATE(23)] = 158,
  [SMALL_STATE(24)] = 184,
  [SMALL_STATE(25)] = 210,
  [SMALL_STATE(26)] = 236,
  [SMALL_STATE(27)] = 264,
  [SMALL_STATE(28)] = 290,
  [SMALL_STATE(29)] = 316,
  [SMALL_STATE(30)] = 342,
  [SMALL_STATE(31)] = 372,
  [SMALL_STATE(32)] = 398,
  [SMALL_STATE(33)] = 426,
  [SMALL_STATE(34)] = 452,
  [SMALL_STATE(35)] = 478,
  [SMALL_STATE(36)] = 504,
  [SMALL_STATE(37)] = 528,
  [SMALL_STATE(38)] = 563,
  [SMALL_STATE(39)] = 597,
  [SMALL_STATE(40)] = 631,
  [SMALL_STATE(41)] = 656,
  [SMALL_STATE(42)] = 678,
  [SMALL_STATE(43)] = 698,
  [SMALL_STATE(44)] = 715,
  [SMALL_STATE(45)] = 732,
  [SMALL_STATE(46)] = 751,
  [SMALL_STATE(47)] = 768,
  [SMALL_STATE(48)] = 787,
  [SMALL_STATE(49)] = 804,
  [SMALL_STATE(50)] = 821,
  [SMALL_STATE(51)] = 834,
  [SMALL_STATE(52)] = 844,
  [SMALL_STATE(53)] = 851,
  [SMALL_STATE(54)] = 858,
  [SMALL_STATE(55)] = 865,
  [SMALL_STATE(56)] = 872,
  [SMALL_STATE(57)] = 879,
  [SMALL_STATE(58)] = 886,
  [SMALL_STATE(59)] = 893,
  [SMALL_STATE(60)] = 900,
  [SMALL_STATE(61)] = 907,
  [SMALL_STATE(62)] = 914,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(22),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(9),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(22),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(53),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(58),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(56),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(56),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(50),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(55),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0), SHIFT(37),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0), REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0), REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [122] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0), REDUCE(aux_sym_array_repeat1, 1, 0, 0), SHIFT(13),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0), SHIFT(15),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_embedded_identifier, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_value, 1, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0), SHIFT(55),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0), SHIFT(27),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_statement, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_statement, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_statement, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition_statement, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 4),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 4),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 4), SHIFT(19),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_map, 4, 0, 5),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_map, 4, 0, 5),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0), SHIFT(19),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_map, 2, 0, 0), REDUCE(sym_array, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_map, 2, 0, 0), REDUCE(sym_array, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_map, 5, 0, 5),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_map, 5, 0, 5),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [220] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0), SHIFT(61),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0), SHIFT(62),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [239] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0), SHIFT(48),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0), SHIFT(43),
  [245] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_paradox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "paradox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
