/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  sym_key = 4,
  sym_literal = 5,
  sym_string = 6,
  sym_number = 7,
  anon_sym_yes = 8,
  anon_sym_no = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  sym_comment = 12,
  sym_source_file = 13,
  sym_statement = 14,
  sym_assignment = 15,
  sym_block = 16,
  sym_value = 17,
  sym_array = 18,
  sym_simple_value = 19,
  sym_boolean = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_array_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_key] = "key",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_yes] = "yes",
  [anon_sym_no] = "no",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_block] = "block",
  [sym_value] = "value",
  [sym_array] = "array",
  [sym_simple_value] = "simple_value",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_key] = sym_key,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_block] = sym_block,
  [sym_value] = sym_value,
  [sym_array] = sym_array,
  [sym_simple_value] = sym_simple_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 13,
  [19] = 19,
  [20] = 8,
  [21] = 9,
  [22] = 22,
  [23] = 12,
  [24] = 11,
  [25] = 10,
  [26] = 26,
  [27] = 27,
};

static const TSCharacterRange sym_key_character_set_1[] = {
  {'!', '!'}, {'$', '%'}, {'-', '.'}, {'0', ':'}, {'<', '<'}, {'>', '>'}, {'@', 'Z'}, {'_', '_'},
  {'a', 'z'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 2,
        '#', 48,
        '-', 23,
        '.', 35,
        '=', 7,
        'f', 10,
        'n', 15,
        't', 16,
        'y', 11,
        '{', 8,
        '}', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('!' <= lookahead && lookahead <= '%') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '@') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 48,
        '-', 23,
        '.', 35,
        'f', 24,
        'n', 29,
        't', 30,
        'y', 25,
        '{', 8,
        '}', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('!' <= lookahead && lookahead <= '%') ||
          lookahead == ':' ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(48);
      if (lookahead == '}') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'a') ADVANCE(14);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(17);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(45);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(47);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(18);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(43);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'r') ADVANCE(19);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 's') ADVANCE(41);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 's') ADVANCE(13);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'u') ADVANCE(12);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_key);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == '+') ADVANCE(3);
      if (lookahead == '-') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'a') ADVANCE(28);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'e') ADVANCE(31);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'e') ADVANCE(44);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'e') ADVANCE(46);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'l') ADVANCE(32);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'o') ADVANCE(42);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'r') ADVANCE(33);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 's') ADVANCE(40);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 's') ADVANCE(27);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'u') ADVANCE(26);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_literal);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_yes);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_yes);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_no);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_no);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_true);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_true);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_false);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(37);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_false);
      if (set_contains(sym_key_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(26),
    [sym_statement] = STATE(15),
    [sym_assignment] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_key] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_statement] = STATE(16),
    [sym_assignment] = STATE(19),
    [sym_block] = STATE(8),
    [sym_value] = STATE(4),
    [sym_array] = STATE(8),
    [sym_simple_value] = STATE(8),
    [sym_boolean] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(16),
    [aux_sym_array_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(11),
    [sym_key] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_string] = ACTIONS(17),
    [sym_number] = ACTIONS(15),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(17),
    [sym_assignment] = STATE(19),
    [sym_block] = STATE(8),
    [sym_value] = STATE(6),
    [sym_array] = STATE(8),
    [sym_simple_value] = STATE(8),
    [sym_boolean] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_array_repeat1] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_key] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_string] = ACTIONS(17),
    [sym_number] = ACTIONS(15),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_block] = STATE(8),
    [sym_value] = STATE(5),
    [sym_array] = STATE(8),
    [sym_simple_value] = STATE(8),
    [sym_boolean] = STATE(13),
    [aux_sym_array_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(23),
    [sym_literal] = ACTIONS(15),
    [sym_string] = ACTIONS(17),
    [sym_number] = ACTIONS(15),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_block] = STATE(8),
    [sym_value] = STATE(5),
    [sym_array] = STATE(8),
    [sym_simple_value] = STATE(8),
    [sym_boolean] = STATE(13),
    [aux_sym_array_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(28),
    [sym_literal] = ACTIONS(30),
    [sym_string] = ACTIONS(33),
    [sym_number] = ACTIONS(30),
    [anon_sym_yes] = ACTIONS(36),
    [anon_sym_no] = ACTIONS(36),
    [anon_sym_true] = ACTIONS(36),
    [anon_sym_false] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_block] = STATE(8),
    [sym_value] = STATE(5),
    [sym_array] = STATE(8),
    [sym_simple_value] = STATE(8),
    [sym_boolean] = STATE(13),
    [aux_sym_array_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(39),
    [sym_literal] = ACTIONS(15),
    [sym_string] = ACTIONS(17),
    [sym_number] = ACTIONS(15),
    [anon_sym_yes] = ACTIONS(19),
    [anon_sym_no] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_block] = STATE(20),
    [sym_value] = STATE(22),
    [sym_array] = STATE(20),
    [sym_simple_value] = STATE(20),
    [sym_boolean] = STATE(18),
    [anon_sym_LBRACE] = ACTIONS(41),
    [sym_literal] = ACTIONS(43),
    [sym_string] = ACTIONS(45),
    [sym_number] = ACTIONS(43),
    [anon_sym_yes] = ACTIONS(47),
    [anon_sym_no] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(47),
    [anon_sym_false] = ACTIONS(47),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(51), 6,
      sym_literal,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [17] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(55), 6,
      sym_literal,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [34] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(59), 6,
      sym_literal,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [51] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(63), 6,
      sym_literal,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [68] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(67), 6,
      sym_literal,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [85] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(71), 6,
      sym_literal,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [102] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      sym_key,
    STATE(19), 1,
      sym_assignment,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
  [120] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_assignment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
  [137] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      sym_assignment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
  [154] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      sym_assignment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
  [171] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [189] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [234] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_key,
  [243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
  [250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 17,
  [SMALL_STATE(10)] = 34,
  [SMALL_STATE(11)] = 51,
  [SMALL_STATE(12)] = 68,
  [SMALL_STATE(13)] = 85,
  [SMALL_STATE(14)] = 102,
  [SMALL_STATE(15)] = 120,
  [SMALL_STATE(16)] = 137,
  [SMALL_STATE(17)] = 154,
  [SMALL_STATE(18)] = 171,
  [SMALL_STATE(19)] = 180,
  [SMALL_STATE(20)] = 189,
  [SMALL_STATE(21)] = 198,
  [SMALL_STATE(22)] = 207,
  [SMALL_STATE(23)] = 216,
  [SMALL_STATE(24)] = 225,
  [SMALL_STATE(25)] = 234,
  [SMALL_STATE(26)] = 243,
  [SMALL_STATE(27)] = 250,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_value, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_paradox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "paradox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
