/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 16
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_if = 4,
  anon_sym_limit = 5,
  anon_sym_trigger = 6,
  anon_sym_potential = 7,
  anon_sym_AND = 8,
  anon_sym_OR = 9,
  anon_sym_NOT = 10,
  anon_sym_LBRACK_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_string = 13,
  sym_number = 14,
  anon_sym_yes = 15,
  anon_sym_no = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  anon_sym_DOLLAR = 19,
  sym_identifier = 20,
  sym_comment = 21,
  sym_source_file = 22,
  sym_assignment = 23,
  sym_map = 24,
  sym_statement = 25,
  sym_array = 26,
  sym_simple_value = 27,
  sym_condition_statement = 28,
  sym_logical_statement = 29,
  sym_macro_map = 30,
  sym_boolean = 31,
  sym_variable = 32,
  sym_variable_embedded_identifier = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_map_repeat1 = 35,
  aux_sym_array_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_limit] = "limit",
  [anon_sym_trigger] = "trigger",
  [anon_sym_potential] = "potential",
  [anon_sym_AND] = "AND",
  [anon_sym_OR] = "OR",
  [anon_sym_NOT] = "NOT",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK] = "]",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_yes] = "yes",
  [anon_sym_no] = "no",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DOLLAR] = "$",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_assignment] = "assignment",
  [sym_map] = "map",
  [sym_statement] = "statement",
  [sym_array] = "array",
  [sym_simple_value] = "simple_value",
  [sym_condition_statement] = "condition_statement",
  [sym_logical_statement] = "logical_statement",
  [sym_macro_map] = "macro_map",
  [sym_boolean] = "boolean",
  [sym_variable] = "variable",
  [sym_variable_embedded_identifier] = "variable_embedded_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_limit] = anon_sym_limit,
  [anon_sym_trigger] = anon_sym_trigger,
  [anon_sym_potential] = anon_sym_potential,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_assignment] = sym_assignment,
  [sym_map] = sym_map,
  [sym_statement] = sym_statement,
  [sym_array] = sym_array,
  [sym_simple_value] = sym_simple_value,
  [sym_condition_statement] = sym_condition_statement,
  [sym_logical_statement] = sym_logical_statement,
  [sym_macro_map] = sym_macro_map,
  [sym_boolean] = sym_boolean,
  [sym_variable] = sym_variable,
  [sym_variable_embedded_identifier] = sym_variable_embedded_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_limit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trigger] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_potential] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_value] = {
    .visible = true,
    .named = true,
  },
  [sym_condition_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_map] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_embedded_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_top_level_statement = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_top_level_statement] = "top_level_statement",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_top_level_statement, 0},
  [1] =
    {field_top_level_statement, 0, .inherited = true},
  [2] =
    {field_top_level_statement, 0, .inherited = true},
    {field_top_level_statement, 1, .inherited = true},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_key, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 12,
  [19] = 13,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 14,
  [27] = 15,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 16,
  [42] = 17,
  [43] = 43,
  [44] = 23,
  [45] = 13,
  [46] = 14,
  [47] = 12,
  [48] = 15,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 51,
  [58] = 51,
  [59] = 55,
  [60] = 55,
};

static const TSCharacterRange sym_identifier_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'%', '<'}, {'>', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 2,
        '#', 70,
        '$', 28,
        '-', 29,
        '.', 67,
        '=', 8,
        'A', 31,
        'N', 32,
        'O', 33,
        '[', 4,
        ']', 19,
        'f', 35,
        'i', 42,
        'l', 45,
        'n', 54,
        'p', 55,
        't', 56,
        'y', 37,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 70,
        '$', 28,
        '-', 29,
        '.', 67,
        '=', 8,
        'f', 35,
        'n', 54,
        't', 58,
        'y', 37,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(69);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '=' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(69);
      END_STATE();
    case 4:
      if (lookahead == '[') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '#', 70,
        '$', 28,
        '-', 29,
        '.', 67,
        '=', 8,
        'A', 31,
        'N', 32,
        'O', 33,
        '[', 4,
        ']', 19,
        'i', 42,
        'l', 45,
        'p', 55,
        't', 59,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead)) ADVANCE(69);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_if);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_limit);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_trigger);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_potential);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_AND);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_OR);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_NOT);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(67);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_yes);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_no);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_true);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_false);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(15);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N') ADVANCE(30);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(34);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(16);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(17);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(51);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(50);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(60);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(27);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(57);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(11);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(44);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(41);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(52);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(43);
      if (lookahead == 'u') ADVANCE(39);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(43);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(62);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(36);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(14);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(61);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(48);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(64);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(25);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(63);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(46);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(13);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(65);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(47);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(24);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(40);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(12);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(38);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(49);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(39);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if ((!eof && set_contains(sym_identifier_character_set_1, 9, lookahead))) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_limit] = ACTIONS(1),
    [anon_sym_trigger] = ACTIONS(1),
    [anon_sym_potential] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(37),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(7),
    [sym_simple_value] = STATE(38),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_boolean] = STATE(42),
    [sym_variable] = STATE(11),
    [sym_variable_embedded_identifier] = STATE(10),
    [aux_sym_map_repeat1] = STATE(7),
    [aux_sym_array_repeat1] = STATE(38),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_string] = ACTIONS(23),
    [sym_number] = ACTIONS(25),
    [anon_sym_yes] = ACTIONS(27),
    [anon_sym_no] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [anon_sym_DOLLAR] = ACTIONS(29),
    [sym_identifier] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(3),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(34),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_if] = ACTIONS(39),
    [anon_sym_limit] = ACTIONS(39),
    [anon_sym_trigger] = ACTIONS(39),
    [anon_sym_potential] = ACTIONS(39),
    [anon_sym_AND] = ACTIONS(42),
    [anon_sym_OR] = ACTIONS(42),
    [anon_sym_NOT] = ACTIONS(42),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(37),
    [sym_number] = ACTIONS(48),
    [anon_sym_DOLLAR] = ACTIONS(51),
    [sym_identifier] = ACTIONS(48),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(37),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(54),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(37),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(56),
    [anon_sym_EQ] = ACTIONS(58),
    [anon_sym_LBRACE] = ACTIONS(61),
    [anon_sym_if] = ACTIONS(64),
    [anon_sym_limit] = ACTIONS(64),
    [anon_sym_trigger] = ACTIONS(64),
    [anon_sym_potential] = ACTIONS(64),
    [anon_sym_AND] = ACTIONS(67),
    [anon_sym_OR] = ACTIONS(67),
    [anon_sym_NOT] = ACTIONS(67),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(70),
    [sym_number] = ACTIONS(73),
    [anon_sym_DOLLAR] = ACTIONS(76),
    [sym_identifier] = ACTIONS(73),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(7),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(3),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(9),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(9),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(83),
    [sym_number] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym_assignment] = STATE(22),
    [sym_map] = STATE(33),
    [sym_statement] = STATE(3),
    [sym_condition_statement] = STATE(22),
    [sym_logical_statement] = STATE(22),
    [sym_macro_map] = STATE(22),
    [sym_variable] = STATE(29),
    [sym_variable_embedded_identifier] = STATE(32),
    [aux_sym_map_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_limit] = ACTIONS(11),
    [anon_sym_trigger] = ACTIONS(11),
    [anon_sym_potential] = ACTIONS(11),
    [anon_sym_AND] = ACTIONS(13),
    [anon_sym_OR] = ACTIONS(13),
    [anon_sym_NOT] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(85),
    [sym_number] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [sym_identifier] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(90),
    [anon_sym_RBRACE] = ACTIONS(92),
    [anon_sym_if] = ACTIONS(95),
    [anon_sym_limit] = ACTIONS(95),
    [anon_sym_trigger] = ACTIONS(95),
    [anon_sym_potential] = ACTIONS(95),
    [anon_sym_AND] = ACTIONS(95),
    [anon_sym_OR] = ACTIONS(95),
    [anon_sym_NOT] = ACTIONS(95),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(90),
    [sym_string] = ACTIONS(97),
    [sym_number] = ACTIONS(99),
    [anon_sym_yes] = ACTIONS(102),
    [anon_sym_no] = ACTIONS(102),
    [anon_sym_true] = ACTIONS(102),
    [anon_sym_false] = ACTIONS(102),
    [anon_sym_DOLLAR] = ACTIONS(92),
    [sym_identifier] = ACTIONS(99),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(90),
    [anon_sym_RBRACE] = ACTIONS(92),
    [anon_sym_if] = ACTIONS(95),
    [anon_sym_limit] = ACTIONS(95),
    [anon_sym_trigger] = ACTIONS(95),
    [anon_sym_potential] = ACTIONS(95),
    [anon_sym_AND] = ACTIONS(95),
    [anon_sym_OR] = ACTIONS(95),
    [anon_sym_NOT] = ACTIONS(95),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(90),
    [sym_string] = ACTIONS(97),
    [sym_number] = ACTIONS(104),
    [anon_sym_yes] = ACTIONS(102),
    [anon_sym_no] = ACTIONS(102),
    [anon_sym_true] = ACTIONS(102),
    [anon_sym_false] = ACTIONS(102),
    [anon_sym_DOLLAR] = ACTIONS(92),
    [sym_identifier] = ACTIONS(104),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [anon_sym_EQ] = ACTIONS(108),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(108),
    [anon_sym_if] = ACTIONS(110),
    [anon_sym_limit] = ACTIONS(110),
    [anon_sym_trigger] = ACTIONS(110),
    [anon_sym_potential] = ACTIONS(110),
    [anon_sym_AND] = ACTIONS(110),
    [anon_sym_OR] = ACTIONS(110),
    [anon_sym_NOT] = ACTIONS(110),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(108),
    [sym_string] = ACTIONS(108),
    [sym_number] = ACTIONS(112),
    [anon_sym_yes] = ACTIONS(110),
    [anon_sym_no] = ACTIONS(110),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [anon_sym_DOLLAR] = ACTIONS(108),
    [sym_identifier] = ACTIONS(112),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [anon_sym_EQ] = ACTIONS(108),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(108),
    [anon_sym_if] = ACTIONS(110),
    [anon_sym_limit] = ACTIONS(110),
    [anon_sym_trigger] = ACTIONS(110),
    [anon_sym_potential] = ACTIONS(110),
    [anon_sym_AND] = ACTIONS(110),
    [anon_sym_OR] = ACTIONS(110),
    [anon_sym_NOT] = ACTIONS(110),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(108),
    [sym_string] = ACTIONS(108),
    [sym_number] = ACTIONS(110),
    [anon_sym_yes] = ACTIONS(110),
    [anon_sym_no] = ACTIONS(110),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [anon_sym_DOLLAR] = ACTIONS(108),
    [sym_identifier] = ACTIONS(110),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [anon_sym_EQ] = ACTIONS(115),
    [anon_sym_LBRACE] = ACTIONS(115),
    [anon_sym_RBRACE] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(117),
    [anon_sym_limit] = ACTIONS(117),
    [anon_sym_trigger] = ACTIONS(117),
    [anon_sym_potential] = ACTIONS(117),
    [anon_sym_AND] = ACTIONS(117),
    [anon_sym_OR] = ACTIONS(117),
    [anon_sym_NOT] = ACTIONS(117),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_number] = ACTIONS(117),
    [anon_sym_yes] = ACTIONS(117),
    [anon_sym_no] = ACTIONS(117),
    [anon_sym_true] = ACTIONS(117),
    [anon_sym_false] = ACTIONS(117),
    [anon_sym_DOLLAR] = ACTIONS(115),
    [sym_identifier] = ACTIONS(117),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [anon_sym_EQ] = ACTIONS(119),
    [anon_sym_LBRACE] = ACTIONS(119),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_if] = ACTIONS(121),
    [anon_sym_limit] = ACTIONS(121),
    [anon_sym_trigger] = ACTIONS(121),
    [anon_sym_potential] = ACTIONS(121),
    [anon_sym_AND] = ACTIONS(121),
    [anon_sym_OR] = ACTIONS(121),
    [anon_sym_NOT] = ACTIONS(121),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(119),
    [sym_string] = ACTIONS(119),
    [sym_number] = ACTIONS(121),
    [anon_sym_yes] = ACTIONS(121),
    [anon_sym_no] = ACTIONS(121),
    [anon_sym_true] = ACTIONS(121),
    [anon_sym_false] = ACTIONS(121),
    [anon_sym_DOLLAR] = ACTIONS(119),
    [sym_identifier] = ACTIONS(121),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_DOLLAR,
    STATE(18), 1,
      sym_variable,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(125), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [29] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(125), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [53] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      sym_number,
      sym_identifier,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(110), 7,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [79] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(110), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(135), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [127] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(139), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(95), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [175] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(143), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [199] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      sym_number,
      sym_identifier,
    ACTIONS(145), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(147), 7,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [225] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(147), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [249] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(117), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [273] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(121), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [297] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(154), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [321] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_EQ,
    ACTIONS(156), 2,
      sym_number,
      sym_identifier,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(95), 7,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [349] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(162), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [373] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(167), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [397] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_EQ,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(95), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(171), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [447] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(175), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [471] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 7,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOLLAR,
    ACTIONS(179), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [495] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(183), 1,
      sym_string,
    STATE(17), 1,
      sym_boolean,
    STATE(24), 1,
      sym_variable,
    ACTIONS(185), 2,
      sym_number,
      sym_identifier,
    ACTIONS(187), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 4,
      sym_map,
      sym_array,
      sym_simple_value,
      sym_variable_embedded_identifier,
  [530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACK_LBRACK,
      anon_sym_DOLLAR,
    ACTIONS(191), 9,
      anon_sym_if,
      anon_sym_limit,
      anon_sym_trigger,
      anon_sym_potential,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      sym_number,
      sym_identifier,
  [552] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_string,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    ACTIONS(197), 1,
      anon_sym_DOLLAR,
    STATE(42), 1,
      sym_boolean,
    STATE(43), 1,
      sym_variable,
    ACTIONS(195), 2,
      sym_number,
      sym_identifier,
    STATE(39), 3,
      sym_simple_value,
      sym_variable_embedded_identifier,
      aux_sym_array_repeat1,
    ACTIONS(27), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [586] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    ACTIONS(201), 1,
      sym_string,
    ACTIONS(210), 1,
      anon_sym_DOLLAR,
    STATE(42), 1,
      sym_boolean,
    STATE(43), 1,
      sym_variable,
    ACTIONS(204), 2,
      sym_number,
      sym_identifier,
    STATE(39), 3,
      sym_simple_value,
      sym_variable_embedded_identifier,
      aux_sym_array_repeat1,
    ACTIONS(207), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [620] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_EQ,
    ACTIONS(215), 1,
      anon_sym_DOLLAR,
    STATE(12), 1,
      sym_variable,
    ACTIONS(123), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(125), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [645] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_DOLLAR,
    STATE(47), 1,
      sym_variable,
    ACTIONS(123), 2,
      anon_sym_RBRACE,
      sym_string,
    ACTIONS(125), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [667] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(125), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [684] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 2,
      sym_number,
      sym_identifier,
    ACTIONS(97), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(102), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [703] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(143), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(110), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [737] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(117), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [754] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 2,
      sym_number,
      sym_identifier,
    ACTIONS(108), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(110), 4,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
  [773] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 3,
      anon_sym_RBRACE,
      sym_string,
      anon_sym_DOLLAR,
    ACTIONS(121), 6,
      sym_number,
      anon_sym_yes,
      anon_sym_no,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(213), 1,
      anon_sym_EQ,
    STATE(18), 1,
      sym_variable,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_map,
  [813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_DOLLAR,
  [820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_identifier,
  [827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_EQ,
  [834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
  [841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_RBRACK,
  [855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_DOLLAR,
  [862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_DOLLAR,
  [869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_identifier,
  [876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(16)] = 0,
  [SMALL_STATE(17)] = 29,
  [SMALL_STATE(18)] = 53,
  [SMALL_STATE(19)] = 79,
  [SMALL_STATE(20)] = 103,
  [SMALL_STATE(21)] = 127,
  [SMALL_STATE(22)] = 151,
  [SMALL_STATE(23)] = 175,
  [SMALL_STATE(24)] = 199,
  [SMALL_STATE(25)] = 225,
  [SMALL_STATE(26)] = 249,
  [SMALL_STATE(27)] = 273,
  [SMALL_STATE(28)] = 297,
  [SMALL_STATE(29)] = 321,
  [SMALL_STATE(30)] = 349,
  [SMALL_STATE(31)] = 373,
  [SMALL_STATE(32)] = 397,
  [SMALL_STATE(33)] = 423,
  [SMALL_STATE(34)] = 447,
  [SMALL_STATE(35)] = 471,
  [SMALL_STATE(36)] = 495,
  [SMALL_STATE(37)] = 530,
  [SMALL_STATE(38)] = 552,
  [SMALL_STATE(39)] = 586,
  [SMALL_STATE(40)] = 620,
  [SMALL_STATE(41)] = 645,
  [SMALL_STATE(42)] = 667,
  [SMALL_STATE(43)] = 684,
  [SMALL_STATE(44)] = 703,
  [SMALL_STATE(45)] = 720,
  [SMALL_STATE(46)] = 737,
  [SMALL_STATE(47)] = 754,
  [SMALL_STATE(48)] = 773,
  [SMALL_STATE(49)] = 790,
  [SMALL_STATE(50)] = 803,
  [SMALL_STATE(51)] = 813,
  [SMALL_STATE(52)] = 820,
  [SMALL_STATE(53)] = 827,
  [SMALL_STATE(54)] = 834,
  [SMALL_STATE(55)] = 841,
  [SMALL_STATE(56)] = 848,
  [SMALL_STATE(57)] = 855,
  [SMALL_STATE(58)] = 862,
  [SMALL_STATE(59)] = 869,
  [SMALL_STATE(60)] = 876,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(33),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(6),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(33),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(53),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(52),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(49),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(55),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0), SHIFT(36),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0), REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0), REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [104] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0), REDUCE(aux_sym_array_repeat1, 1, 0, 0), SHIFT(13),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0), SHIFT(14),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_embedded_identifier, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_value, 1, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0), SHIFT(55),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0), SHIFT(26),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_statement, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_statement, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 4),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 4), SHIFT(19),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_map, 4, 0, 5),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_map, 4, 0, 5),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0), SHIFT(19),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_map, 2, 0, 0), REDUCE(sym_array, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_map, 2, 0, 0), REDUCE(sym_array, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_statement, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition_statement, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_map, 5, 0, 5),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_map, 5, 0, 5),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0), SHIFT(59),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_simple_value, 1, 0, 0), SHIFT(60),
  [221] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0), SHIFT(45),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_variable_embedded_identifier, 2, 0, 0), SHIFT(46),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [233] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_paradox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "paradox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
