name: Regenerate parser

on:
    workflow_dispatch:
    pull_request:

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    regenerate:
        uses: tree-sitter/workflows/.github/workflows/regenerate.yml@main
        if: github.actor == 'dependabot[bot]'
